# write a python script print only part of string .take input of sart character and enter character from user.

def  stringSUB(string)
    startindex=int(input("\n enter string for substring:")
    endindex=int(input("\n enter string for subsring:")
    print(f"\n stringSUB which start form {startindex} index is -- {string[startindex-1:endindex+1]}")
 string=input("\n enter string:")
 stringSUB(STRING)                
                 
